### PR TITLE
Import fix for LocalSvg

### PR DESCRIPTION
**Pull request by maheshwarimrinal**
Import fix for `LocalSvg` prop from `react-native-svg`

### CODE REVIEW

**Comment by maheshwarimrinal** [comment]
@justinpersaud @AndrewGable @luacmartins 

Can you guys review the pull request.

**Review by luacmartins — APPROVED** [review]

**Comment by luacmartins** [comment]
@Kicu wanna take a look at this one too before we merge?

**Comment by Kicu** [comment]
@maheshwarimrinal can we get any context and description what specifically breaks and what this fixes?
Was this never working?

**Review by luacmartins — CHANGES_REQUESTED** [review]
@maheshwarimrinal after discussing with the team, it seems like this change doesn't really make sense. Could you provide more context on what issue this is fixing?

**Comment by maheshwarimrinal** [comment]
Looks like we are using old version of react-native-svg which was causing issue, that's why opened the PR. After updating it worked fine.

Closing the PR.

**Comment by Kicu** [comment]
@luacmartins I will provide a PR today that bumps the minimal version of `react-native-svg` in our package.json to avoid this confusion in future.

**Pull request closed without merging**
