### PR TITLE
Publish via npm using a new bot and signing method

### PR DESCRIPTION
**Pull request by AndrewGable**
## Details

Related issue describing why we are doing this: https://github.com/Expensify/Expensify/issues/432173

This PR changes how we publish this `npm` package to `npmjs` using our shared publish workflow. This workflow is improved as it aligns all `npm` packages to use the same shared workflow and reduces the need to store a private GPG key increasing our security.

## Tests

All you need to do to test this is merge this PR and I will verify the latest version is published to NPM.

### CODE REVIEW

**Review by justinpersaud — APPROVED** [review]

**Comment by justinpersaud** [comment]
whoops sorry @luacmartins didn't see you as a reviewer too

**Comment by AndrewGable** [comment]
@justinpersaud - Do you mind double checking that OSBotify[bot] (The GitHub app) has access to this repo? Seems like no from this error: https://github.com/Expensify/react-native-qrcode-svg/actions/runs/11372041143/job/31635468273

**Comment by justinpersaud** [comment]
Adding it now. Seems like we'll need to add it for each repo you use this in. Is there a full list?

image

**Comment by justinpersaud** [comment]
You have a new error https://github.com/Expensify/react-native-qrcode-svg/actions/runs/11372041143/job/31640728935

**Comment by AndrewGable** [comment]
Thanks, I can work with @johnmlee101 in https://github.com/Expensify/Expensify/issues/432173 to make sure all repos are added.

**Comment by AndrewGable** [comment]
Publish should be working as intended now, please ping me if it stops working in the future.

**Pull request merged**
